Repository BreatheLion/BreatheLion_backend, pull requests merged in 2025-08, with the labels that each got.

#2 Feat/1 record entity
  .DS_Store
  .github/PULL_REQUEST_TEMPLATE.md
  .gradle/8.14.3/checksums/checksums.lock
  .gradle/8.14.3/checksums/md5-checksums.bin
  .gradle/8.14.3/checksums/sha1-checksums.bin
  .gradle/8.14.3/executionHistory/executionHistory.bin
  .gradle/8.14.3/executionHistory/executionHistory.lock
  .gradle/8.14.3/fileHashes/fileHashes.bin
  .gradle/8.14.3/fileHashes/fileHashes.lock
  .gradle/8.14.3/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/BreatheLion_backend.main.iml
  build.gradle
  build/classes/java/main/YAMSABU/BreatheLion_backend/BreatheLionBackendApplication.class
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/YAMSABU/.DS_Store
  src/main/java/YAMSABU/BreatheLion_backend/.DS_Store
  src/main/java/YAMSABU/BreatheLion_backend/drawer/entity/Drawer.java
  src/main/java/YAMSABU/BreatheLion_backend/record/.DS_Store
  src/main/java/YAMSABU/BreatheLion_backend/record/entity/Record.java
  src/main/java/YAMSABU/BreatheLion_backend/record/entity/RecordCategory.java
  src/main/java/YAMSABU/BreatheLion_backend/record/repository/RecordRepository.java
Labels: ⚙ Setting, ✨ Feature, 📃 Docs

#6 Feat/3 person+chat+evidence
  .gradle/8.14.3/checksums/checksums.lock
  .gradle/8.14.3/checksums/md5-checksums.bin
  .gradle/8.14.3/checksums/sha1-checksums.bin
  .idea/modules.xml
  src/main/java/YAMSABU/BreatheLion_backend/chat/entity/ChatLog.java
  src/main/java/YAMSABU/BreatheLion_backend/chat/entity/ChatRole.java
  src/main/java/YAMSABU/BreatheLion_backend/chat/entity/ChatSession.java
  src/main/java/YAMSABU/BreatheLion_backend/evidence/entity/Evidence.java
  src/main/java/YAMSABU/BreatheLion_backend/evidence/entity/EvidenceType.java
  src/main/java/YAMSABU/BreatheLion_backend/person/entity/Person.java
  src/main/java/YAMSABU/BreatheLion_backend/person/entity/PersonRole.java
  src/main/java/YAMSABU/BreatheLion_backend/record/RecordPerson.java
  src/main/java/YAMSABU/BreatheLion_backend/record/entity/Record.java
Labels: ✨ Feature

#15 chore: remove Gradle/IDE caches and update .gitignore
  .gitignore
  .gradle/8.14.3/checksums/checksums.lock
  .gradle/8.14.3/checksums/md5-checksums.bin
  .gradle/8.14.3/checksums/sha1-checksums.bin
  .gradle/8.14.3/executionHistory/executionHistory.bin
  .gradle/8.14.3/executionHistory/executionHistory.lock
  .gradle/8.14.3/fileChanges/last-build.bin
  .gradle/8.14.3/fileHashes/fileHashes.bin
  .gradle/8.14.3/fileHashes/fileHashes.lock
  .gradle/8.14.3/fileHashes/resourceHashesCache.bin
  .gradle/8.14.3/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
Labels: ⚙ Setting, 🔨 Refactor

#29 Feat/chat load + Refact/구조 수정
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/controller/ChatController.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/converter/ChatConverter.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/dto/ChatDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/entity/Chat.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/entity/Session.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/service/ChatService.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/service/ChatServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/controller/DrawerController.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/dto/DrawerDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/service/DrawerServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/evidence/controller/EvidenceController.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/evidence/dto/EvidenceDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/evidence/entity/Evidence.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/evidence/entity/EvidenceType.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/evidence/repository/EvidenceRepository.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/person/dto/EvidenceDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/person/entity/Person.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/converter/RecordConverter.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/dto/RecordDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/entity/Record.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/entity/RecordCategory.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/entity/RecordPerson.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/repository/RecordRepository.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/service/RecordService.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/service/RecordServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/controller/AIController.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/dto/AIAnswerDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/prompt/PromptStore.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/service/AIService.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/service/AIServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/global/pdf/PdfExportService.java
  src/main/resources/application.yml
  src/test/java/YAMSABU/BreatheLion_backend/BreatheLionBackendApplicationTests.java
Labels: ✨ Feature, 🔨 Refactor

#39 Refact/38 api CORS 문법 추가 + 코드 리팩토링
  src/main/java/YAMSABU/BreatheLion_backend/domain/WebConfig.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/converter/ChatConverter.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/chat/entity/Session.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/controller/DrawerController.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/converter/DrawerConverter.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/entity/Drawer.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/entity/Law.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/repository/DrawerRepository.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/service/DrawerServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/evidence/controller/EvidenceController.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/organization/entity/DrawerOrganization.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/organization/entity/Organization.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/organization/repository/OrganizationRepository.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/person/entity/Person.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/controller/RecordController.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/dto/RecordDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/service/RecordService.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/service/RecordServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/dto/AIAnswerDTO.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/prompt/PromptStore.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/service/AIService.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/service/AIServiceImpl.java
Labels: 🔨 Refactor

#62 feat : organization 부여
  docker-compose.yaml
  src/main/java/YAMSABU/BreatheLion_backend/domain/WebConfig.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/organization/config/OrgConfig.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/organization/repository/OrganizationRepository.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/prompt/PromptStore.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/service/AIServiceImpl.java
Labels: ⚙ Setting

#65 feat : 예외처리
  src/main/java/YAMSABU/BreatheLion_backend/domain/WebConfig.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/repository/DrawerRepository.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/drawer/service/DrawerServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/domain/record/service/RecordServiceImpl.java
  src/main/java/YAMSABU/BreatheLion_backend/global/ai/prompt/PromptStore.java
  src/main/java/YAMSABU/BreatheLion_backend/global/pdf/PdfServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor
